# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ba422cc2aecefbc359b6880e4540c60ef80edc799824b196dee0d02cf4cb64f5748fd7d34d101745eb40f235c9173aae1917e9dc194e0ae9a466d8ceb78a410

test:
  secret_key_base: e06a519b7c8c5eab5576984d65d7aace5e6d8db86cf30bc52f4dacd6d75974599691b52f0d7d29b3e382e1c96e5e815be47b98296a08a1e6bf4c1f6e631a3687

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
